name: Monitoramento de Produtos iFood

on:
  schedule:
    - cron: '0 14-23,0-2 * * *'  # Formato simplificado (14h-2h UTC = 11h-23h BRT)
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Previne execuções muito longas

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4  # Atualizado para versão 4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'  # Habilita cache automático

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas openpyxl gspread oauth2client requests
          # Remova o -r requirements.txt se não estiver usando

      - name: Configurar Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'  # Garante a versão mais recente

      - name: Executar monitoramento
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Padronizado
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          # Verificação pré-execução
          echo "Python version: $(python --version)"
          echo "Pip version: $(pip --version)"
          python monitoramento_produtos_actions.py || exit 1

      - name: Publicar no GitHub Pages
        if: success()  # Só executa se o passo anterior for bem-sucedido
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Padronizado
          publish_branch: gh-pages
          publish_dir: ./
          keep_files: true  # Mantém arquivos existentes
