name: Monitoramento de Produtos iFood

on:
  schedule:
    # Executa a cada hora das 11:00 às 23:00 (UTC)
    - cron: '0 11-23 * * *'
  workflow_dispatch:  # Permite execução manual

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas openpyxl requests webdriver-manager
        
    - name: Instalar Chrome e ChromeDriver
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
        
    - name: Executar monitoramento
      run: python monitoramento_produtos_actions.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        
    - name: Configurar GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        force_orphan: true
